# PYTHON PROGRAMMING FUNDAMENTALS - PART B


This Notebook will cover the following topics:    
- Numpy basics
- Built-in methods and functions 
- Obtain shape, length and type of Numpy arrays
- Reshape 
- Minimum and maximum and their indices
- Mathematical Operations
- Indexing and slicing 
- Selection 



# NUMPY BASICS
- NumPy is a Linear Algebra Library used for multidimensional arrays
- Installation: Use the command window, type: conda install numpy

In [7]:
import numpy as np 

In [21]:
# One-dimensional array 
my_list = [5, 3, 10,20]
my_list

[5, 3, 10, 20]

In [9]:
y = np.array(my_list)

In [22]:
y

array([ 5,  3, 10, 20])

In [23]:
type(y)

numpy.ndarray

In [6]:
# multi-dimensional (Matrix definition) 
matrix = np.array([[1, 2], [3, 4]])

In [7]:
matrix

array([[1, 2],
       [3, 4]])

# BUILT-IN METHODS AND FUNCTIONS

In [8]:
# "rand()" uniform distribution between 0 and 1
x = np.random.rand(10)
x

array([0.5198945 , 0.13523158, 0.80818111, 0.57538452, 0.97865453,
       0.1616179 , 0.57281699, 0.65615678, 0.13921355, 0.93660582])

In [10]:
x = np.random.rand(10, 10)
x

array([[0.2522071 , 0.44026058, 0.61978782, 0.14499514, 0.08194718,
        0.28407936, 0.83801001, 0.47568682, 0.80480758, 0.10761258],
       [0.9225992 , 0.99237281, 0.50572929, 0.34726042, 0.87769937,
        0.27573731, 0.19127976, 0.94274868, 0.30923872, 0.87756751],
       [0.09960265, 0.61027959, 0.68334569, 0.21018195, 0.75811873,
        0.14263352, 0.55752572, 0.69751185, 0.24419382, 0.98109616],
       [0.41884433, 0.10791954, 0.4323494 , 0.36495341, 0.94901939,
        0.98195132, 0.91791265, 0.50387357, 0.00376472, 0.12564814],
       [0.49858195, 0.60811648, 0.07077767, 0.93585665, 0.11210376,
        0.23988139, 0.46499008, 0.11074481, 0.78224042, 0.11118211],
       [0.83162622, 0.53237487, 0.59563727, 0.21621803, 0.32531719,
        0.85042331, 0.99534214, 0.44646231, 0.13793371, 0.15355439],
       [0.57205662, 0.19982232, 0.34375639, 0.37768349, 0.87958694,
        0.6130539 , 0.49438321, 0.68433823, 0.83368692, 0.55799126],
       [0.93477962, 0.49876673, 0.2759269

In [11]:
# "randn()" normal distribution between 0 and 1
x = np.random.randn(10)
x

array([-1.45195198,  0.2782095 , -0.48220699,  2.06386169, -0.47526995,
       -1.36745553,  0.47464606, -0.3004339 , -0.02892385, -0.22571796])

In [25]:
# "randint" is used to generate random integers between upper and lower bounds
x = np.random.randint(1, 10)
x

5

In [27]:
# "randint" is used to generate random integers between upper and lower bounds
x = np.random.randint(1, 100, 15)
x

array([ 4, 28, 85, 75,  4, 11,  6, 47, 26, 43, 35, 41, 45, 69, 16])

In [28]:
x = np.arange(1, 50)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [29]:
x = np.arange(1, 50, 5)
x

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

In [31]:
x = np.eye(5)
x

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
# Array of ones
x = np.ones(15)
x

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [34]:
# Matrices of ones
x = np.ones((15, 15))
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.

In [35]:
x.shape

(15, 15)

In [27]:
x = np.zeros(50)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

# SHAPE, LENGTH AND TYPE OF NUMPY ARRAYS

In [28]:
# get Length 
len(y)

3

In [29]:
# get shape
y.shape

(3,)

In [30]:
matrix.shape

(2, 2)

In [36]:
matrix.dtype

dtype('int32')

# RESHAPE

In [37]:
y = np.array([3, 5, 7, 8])
y.reshape(2,2)

array([[3, 5],
       [7, 8]])

# MAX AND MIN VALUES AND THEIR INDEX

In [38]:
y.max()

8

In [39]:
y.min()

3

In [40]:
# Obtain the index of the max value
y.argmax()

3

In [41]:
# Obtain the index of the min value
y.argmin()

0

# MATHEMATICAL OPERATIONS

In [42]:
x = np.arange(1, 5)
x

array([1, 2, 3, 4])

In [43]:
y = np.arange(1, 5)
z = x+y
z

array([2, 4, 6, 8])

In [44]:
z = x**2
z

array([ 1,  4,  9, 16], dtype=int32)

In [45]:
k = np.sqrt(z)
k

array([1., 2., 3., 4.])

In [46]:
z = np.exp(y)
z

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

# ELEMENTS SLICING AND INDEXING

In [47]:
x = np.random.randint(1,10, 10)
x

array([3, 1, 2, 9, 3, 8, 8, 9, 6, 1])

In [49]:
x[3]

9

In [50]:
x[0:3]

array([3, 1, 2])

In [52]:
# Broadcasting, altering several values in a numpy array at once
x[0:6] = 10
x

array([10, 10, 10, 10, 10, 10,  8,  9,  6,  1])

In [53]:
matrix = np.random.randint(1,10, (5, 5))
matrix

array([[4, 1, 6, 9, 5],
       [6, 9, 9, 4, 2],
       [4, 7, 5, 6, 3],
       [3, 7, 8, 7, 6],
       [1, 8, 6, 4, 3]])

In [55]:
# Get a row from a mtrix
matrix[2]

array([4, 7, 5, 6, 3])

In [56]:
# Get element
matrix[0][2]

6

In [58]:
mini_matrix = matrix[:3]
mini_matrix

array([[4, 1, 6, 9, 5],
       [6, 9, 9, 4, 2],
       [4, 7, 5, 6, 3]])

In [20]:
mini_matrix = matrix[2:]
mini_matrix

array([[3, 2, 4, 5, 4],
       [1, 7, 7, 4, 3],
       [1, 1, 4, 3, 5]])

In [60]:
mini_matrix = matrix[:, :2]
mini_matrix

array([[4, 1],
       [6, 9],
       [4, 7],
       [3, 7],
       [1, 8]])

In [61]:
mini_matrix = matrix[:, 2:]
mini_matrix

array([[6, 9, 5],
       [9, 4, 2],
       [5, 6, 3],
       [8, 7, 6],
       [6, 4, 3]])

# ELEMENTS SELECTION

In [15]:
matrix = np.random.randint(1,10, (5, 5))
matrix

array([[4, 8, 4, 4, 3],
       [2, 9, 2, 2, 1],
       [3, 2, 4, 5, 4],
       [1, 7, 7, 4, 3],
       [1, 1, 4, 3, 5]])

In [16]:
new_matrix = matrix[matrix>3]
new_matrix

array([4, 8, 4, 4, 9, 4, 5, 4, 7, 7, 4, 4, 5])

In [17]:
new_matrix = matrix[matrix%2==0]
new_matrix

array([4, 8, 4, 4, 2, 2, 2, 2, 4, 4, 4, 4])

# NOW YOU HAVE MASTERED NUMPY, GIVE YOURSELF A PAT ON THE SHOULDER!

In [19]:
mini_matrix = matrix[:, 2:]
mini_matrix

array([[4, 4, 3],
       [2, 2, 1],
       [4, 5, 4],
       [7, 4, 3],
       [4, 3, 5]])